{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.ingress.serviceName  -}}
{{- $servicePort := .Values.ingress.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
  {{- end }}
  {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.nameSpace }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ $fullName }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: 
        pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific"}} 
        backend:
          service:
            name: {{ $fullName }}
            port: 
              number: {{ $servicePort }}
{{- end }}